name: simple_note_app
environment:
  sdk: '>=3.0.0 <4.0.0'
flutter:
  uses-material-design: true
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  path_provider: ^2.1.0
  provider: ^6.1.0
  intl: ^0.18.0
  fluttertoast: ^8.2.2
  
